function mobile(){var lb='',X=' top: -1000px;',ub='" for "gwt:onLoadErrorFn"',sb='" for "gwt:onPropertyErrorFn"',eb='");',vb='#',Hb='&',hc='.cache.js',xb='/',Db='//',_b='02006ED8504E780B5E4305352B815B6B',bc='14E1A50848D7983653E404054DD66FC3',cc='4B9546F81B72DF50F457DCA87598E548',dc='668EAE8649CA4D7EE59CF7FEDEF4159E',gc=':',mb='::',Jb=';',Y='<html><head><\/head><body><\/body><\/html>',pb='=',wb='?',ec='AFC5DD32692C1FFE0BE778CE15767B77',rb='Bad handler "',cb='Chrome',fc='D468E851DA230B9B374145CDF24EA95C',bb='DOMContentLoaded',S='DUMMY',Ib='MOBILE_LOCALE=',Mb='Unexpected exception in locale detection, using default: ',Kb='_',Lb='__gwt_Locale',Cb='base',Ab='baseUrl',N='begin',T='body',M='bootstrap',zb='clear.cache.gif',ob='content',$b='default',Fb='en',jc='end',db='eval("',Vb='gecko',Wb='gecko1_8',O='gwt.codesvr.mobile=',P='gwt.codesvr=',tb='gwt:onLoadErrorFn',qb='gwt:onPropertyErrorFn',nb='gwt:property',hb='head',Ub='ie6',Tb='ie8',Sb='ie9',U='iframe',yb='img',ac='ja',$='javascript',V='javascript:""',ic='loadExternalRefs',Eb='locale',Gb='locale=',ib='meta',Q='mobile',Zb='mobile.devmode.js',Bb='mobile.nocache.js',kb='mobile::',gb='moduleRequested',fb='moduleStartup',Rb='msie',jb='name',Ob='opera',W='position:absolute; width:0; height:0; border:none; left: -1000px;',Qb='safari',Z='script',Yb='selectingPermutation',R='startup',ab='undefined',Xb='unknown',Nb='user.agent',_='var $wnd = window.parent;',Pb='webkit';var u=window;var v=document;x(M,N);function w(){var a=u.location.search;return a.indexOf(O)!=-1||a.indexOf(P)!=-1}
function x(a,b){if(u.__gwtStatsEvent){u.__gwtStatsEvent({moduleName:Q,sessionId:u.__gwtStatsSessionId,subSystem:R,evtGroup:a,millis:(new Date).getTime(),type:b})}}
mobile.__sendStats=x;mobile.__moduleName=Q;mobile.__errFn=null;mobile.__moduleBase=S;mobile.__softPermutationId=0;mobile.__computePropValue=null;mobile.__getPropMap=null;mobile.__gwtInstallCode=function(){};mobile.__gwtStartLoadingFragment=function(){return null};var y=function(){return false};var z=function(){return null};__propertyErrorFunction=null;var A=u.__gwt_activeModules=u.__gwt_activeModules||{};A[Q]={moduleName:Q};var B;function C(){E();return B}
function D(){E();return B.getElementsByTagName(T)[0]}
function E(){if(B){return}var a=v.createElement(U);a.src=V;a.id=Q;a.style.cssText=W+X;a.tabIndex=-1;v.body.appendChild(a);B=a.contentDocument;if(!B){B=a.contentWindow.document}B.open();B.write(Y);B.close();var b=B.getElementsByTagName(T)[0];var c=B.createElement(Z);c.language=$;var d=_;c.text=d;b.appendChild(c)}
function F(k){function l(a){function b(){if(typeof v.readyState==ab){return typeof v.body!=ab&&v.body!=null}return /loaded|complete/.test(v.readyState)}
var c=b();if(c){a();return}function d(){if(!c){c=true;a();if(v.removeEventListener){v.removeEventListener(bb,d,false)}if(e){clearInterval(e)}}}
if(v.addEventListener){v.addEventListener(bb,d,false)}var e=setInterval(function(){if(b()){d()}},50)}
function m(c){function d(a,b){a.removeChild(b)}
var e=D();var f=C();var g;if(navigator.userAgent.indexOf(cb)>-1&&window.JSON){var h=f.createDocumentFragment();h.appendChild(f.createTextNode(db));for(var i=0;i<c.length;i++){var j=window.JSON.stringify(c[i]);h.appendChild(f.createTextNode(j.substring(1,j.length-1)))}h.appendChild(f.createTextNode(eb));g=f.createElement(Z);g.language=$;g.appendChild(h);e.appendChild(g);d(e,g)}else{for(var i=0;i<c.length;i++){g=f.createElement(Z);g.language=$;g.text=c[i];e.appendChild(g);d(e,g)}}}
mobile.onScriptDownloaded=function(a){l(function(){m(a)})};x(fb,gb);var n=v.createElement(Z);n.src=k;v.getElementsByTagName(hb)[0].appendChild(n)}
mobile.__startLoadingFragment=function(a){return I(a)};mobile.__installRunAsyncCode=function(a){var b=D();var c=C().createElement(Z);c.language=$;c.text=a;b.appendChild(c);b.removeChild(c)};function G(){var c={};var d;var e;var f=v.getElementsByTagName(ib);for(var g=0,h=f.length;g<h;++g){var i=f[g],j=i.getAttribute(jb),k;if(j){j=j.replace(kb,lb);if(j.indexOf(mb)>=0){continue}if(j==nb){k=i.getAttribute(ob);if(k){var l,m=k.indexOf(pb);if(m>=0){j=k.substring(0,m);l=k.substring(m+1)}else{j=k;l=lb}c[j]=l}}else if(j==qb){k=i.getAttribute(ob);if(k){try{d=eval(k)}catch(a){alert(rb+k+sb)}}}else if(j==tb){k=i.getAttribute(ob);if(k){try{e=eval(k)}catch(a){alert(rb+k+ub)}}}}}z=function(a){var b=c[a];return b==null?null:b};__propertyErrorFunction=d;mobile.__errFn=e}
function H(){function e(a){var b=a.lastIndexOf(vb);if(b==-1){b=a.length}var c=a.indexOf(wb);if(c==-1){c=a.length}var d=a.lastIndexOf(xb,Math.min(c,b));return d>=0?a.substring(0,d+1):lb}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=v.createElement(yb);b.src=a+zb;a=e(b.src)}return a}
function g(){var a=z(Ab);if(a!=null){return a}return lb}
function h(){var a=v.getElementsByTagName(Z);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(Bb)!=-1){return e(a[b].src)}}return lb}
function i(){var a=v.getElementsByTagName(Cb);if(a.length>0){return a[a.length-1].href}return lb}
function j(){var a=v.location;return a.href==a.protocol+Db+a.host+a.pathname+a.search+a.hash}
var k=g();if(k==lb){k=h()}if(k==lb){k=i()}if(k==lb&&j()){k=e(v.location.href)}k=f(k);return k}
function I(a){if(a.match(/^\//)){return a}if(a.match(/^[a-zA-Z]+:\/\//)){return a}return mobile.__moduleBase+a}
function J(){var m=[];var n;function o(a,b){var c=m;for(var d=0,e=a.length-1;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
var p=[];var q=[];function r(a){var b=q[a](),c=p[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(__propertyErrorFunc){__propertyErrorFunc(a,d,b)}throw null}
q[Eb]=function(){var b=null;var c=Fb;try{if(!b){var d=location.search;var e=d.indexOf(Gb);if(e>=0){var f=d.substring(e+7);var g=d.indexOf(Hb,e);if(g<0){g=d.length}b=d.substring(e+7,g)}}if(!b){var h=v.cookie;var i=h.indexOf(Ib);if(i>=0){var g=h.indexOf(Jb,i);if(g<0){g=h.length}b=h.substring(i+14,g)}}if(!b){b=z(Eb)}if(!b){var j=navigator.browserLanguage?navigator.browserLanguage:navigator.language;if(j){var k=j.split(/[-_]/);if(k.length>1){k[1]=k[1].toUpperCase()}b=k.join(Kb)}}if(!b){b=u[Lb]}if(b){c=b}while(b&&!y(Eb,b)){var l=b.lastIndexOf(Kb);if(l<0){b=null;break}b=b.substring(0,l)}}catch(a){alert(Mb+a)}u[Lb]=c;return b||Fb};p[Eb]={'default':0,en:1,ja:2};q[Nb]=function(){var b=navigator.userAgent.toLowerCase();var c=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(function(){return b.indexOf(Ob)!=-1}())return Ob;if(function(){return b.indexOf(Pb)!=-1}())return Qb;if(function(){return b.indexOf(Rb)!=-1&&v.documentMode>=9}())return Sb;if(function(){return b.indexOf(Rb)!=-1&&v.documentMode>=8}())return Tb;if(function(){var a=/msie ([0-9]+)\.([0-9]+)/.exec(b);if(a&&a.length==3)return c(a)>=6000}())return Ub;if(function(){return b.indexOf(Vb)!=-1}())return Wb;return Xb};p[Nb]={gecko1_8:0,ie6:1,ie8:2,ie9:3,opera:4,safari:5};y=function(a,b){return b in p[a]};mobile.__getPropMap=function(){var a={};for(var b in p){a[b]=r(b)}return a};mobile.__computePropValue=r;u.__gwt_activeModules[Q].bindings=mobile.__getPropMap;x(M,Yb);if(w()){return I(Zb)}var s;try{o([$b,Ub],_b);o([Fb,Ub],_b);o([ac,Ub],_b);o([$b,Tb],bc);o([Fb,Tb],bc);o([ac,Tb],bc);o([$b,Ob],cc);o([Fb,Ob],cc);o([ac,Ob],cc);o([$b,Wb],dc);o([Fb,Wb],dc);o([ac,Wb],dc);o([$b,Qb],ec);o([Fb,Qb],ec);o([ac,Qb],ec);o([$b,Sb],fc);o([Fb,Sb],fc);o([ac,Sb],fc);s=m[r(Eb)][r(Nb)];var t=s.indexOf(gc);if(t!=-1){n=parseInt(s.substring(t+1),10);s=s.substring(0,t)}}catch(a){}mobile.__softPermutationId=n;return I(s+hc)}
function K(){if(!u.__gwt_stylesLoaded){u.__gwt_stylesLoaded={}}x(ic,N);x(ic,jc)}
G();mobile.__moduleBase=H();A[Q].moduleBase=mobile.__moduleBase;var L=J();K();x(M,jc);F(L);return true}
mobile.succeeded=mobile();